version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(name)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/scraper.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  news_aggregator:
    level: DEBUG
    handlers: [ console, file ]
    propagate: true

root:
  level: INFO
  handlers: [ console ]
  propagate: true